GANDRIVING:
  FOM_INPUT_IMAGE: './Input/test.png'
  FOM_DRIVING_VIDEO: './Input/zimeng.mp4'
  FOM_OUTPUT_VIDEO: './Input/test.mp4'

TTS:
  SPEED: 0.9
  PITCH: 1.0
  ENERGY: 1.0

SAVEPATH:
  VIDEO_SAVE_PATH: './Output/video/'
  AUDIO_SAVE_PATH: './Output/audio/'